project:
  type: website

website:
  navbar:
    # logo: super_sep.jpg 
    title: "Sep Dadsetan"
    background: primary
    search: true
    right:
      - about.qmd

format:
  html:
    include-in-header: 
      - fonts.html
    theme: custom.scss



