project:
  type: website
  
website: 
  title: "sepd.dev"
  description: "Sep Dadsetan's personal site"
  page-navigation: true
  site-url: "https://sepd.dev" 
  repo-url: https://github.com/phdjsep/sepd-dev 
  repo-actions: []
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Sep Dadsetan, 2023"
    
  sidebar:
    title: "sepd.dev"
    logo: "assets/img/sepd_dev_hex.png"
    pinned: true
    align: center
    tools: 
      - icon: linkedin
        href: https://www.linkedin.com/in/sepdadsetan/
        text: "LinkedIn"
      - icon: github
        href: https://github.com/phdjsep/
        text: "Github"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: about.qmd
        text: About Me

format:
  html:
    include-in-header: 
      - text: |
          <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
          <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
          <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
          <link rel="manifest" href="/site.webmanifest">
          <link rel="me" href="https://mastodon.social/@phdjsep">
    theme:
      light: [cosmo, assets/styles/light.scss]
      # dark: [cosmo, assets/styles/dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: false

execute:
  freeze: auto
  