---
title: "About"
about:
  template: solana
format:
  html:
    css: 'assets/styles/styles.css'
---

Hello! I'm Sep, currently Director, RWD Analytics at Labcorp. I have over 12 years of experience in analytics, engineering, and real-world data. I thrive in fast-paced, innovation-driven industries where I can apply my generalist skills to solve complex problems and create value.

## My Background

I hold a B.S. degree in Genetics and a Ph.D. in Molecular, Cellular, and Integrative Physiology from UC Davis (Go Aggies!), and my career has spanned Life Sciences, Pharma, Technology companies. 

## What I Do

I specialize in blending technical expertise with strategic thinking to solve complex problems and drive impact. Over the years, my work has focused on:

- **Real-World Data Analytics**: Leveraging structured and curated data, including EMR, claims, and genomic/biomarker datasets, to generate actionable insights. I support teams in clinical effectiveness studies, patient cohort characterization, and treatment journey mapping, enabling data-driven decisions that improve patient outcomes and operational efficiency.

- **Leadership and Cross-Functional Collaboration**: Defining organizational data strategies and aligning stakeholders across business and technical teams. I lead initiatives that prioritize high-impact use cases and deliver innovative, data-driven solutions while fostering collaboration across diverse teams.

- **Insights and Analytics for Strategic Decision-Making**: Translating complex data into clear, actionable insights for clinical trial planning, business performance improvement, and strategic growth. My work involves developing analytics frameworks, uncovering opportunities, and effectively communicating findings to senior stakeholders to influence high-level decisions.

These areas of expertise allow me to navigate the intersection of data, technology, and strategy, delivering solutions that create value for organizations and the people they serve.

## My Interests

I'm passionate about technology, health, and storytelling to tackle challenges in oncology (and other meaningful domains). Outside of work, I enjoy spending time with my family, dj'ing, and playing footgolf.

## Let's Connect

If you're interested in collaborating or learning more about my work, feel free to reach out! You can find me on:

- **[LinkedIn](https://www.linkedin.com/in/sepdadsetan/)**  

Thanks for stopping by!